---
title: "Modeling_CODE"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_width: 14
    fig_height: 10
    fig.align : 'center'
    toc: yes
    number_sections : yes
    code_folding: show
    keep_md: true
---

<hr>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)
```

<style type="text/css">
.main-container {
max-width: 1200px;
margin-left: auto;
margin-right: auto;
}
</style>


# Load package
```{r}
rm(list=ls())

#load packages
library(knitr)
library(tidyverse)
library(magrittr)
library(tidymodels)
library(caret)

options(scipen=999) # turn-off scientific notation like 1e+48
options(tibble.width = Inf)
```

<hr>

<div style="margin-bottom:60px;">
</div>

# Import Data 
```{r}
train <- train %>% mutate(Dayofweek = as.character(Dayofweek))
test <- test %>% mutate(Dayofweek = as.character(Dayofweek))

submission <- read_csv("./data/sample_submission.csv")
```

<hr>

<div style="margin-bottom:60px;">
</div>

# Modeling

## N_lunch

```{r}
# Make recipe

train_recipe <- train %>% 
  recipe(N_lunch ~ .) %>%
  step_rm(Date, Breakfast, Lunch, Dinner, N_dinner, Rate_lunch, Rate_dinner, starts_with("Lunch_"), starts_with("Dinner_")) %>%
  step_string2factor(all_nominal())

set.seed(2021)
cv_folds <- train %>% vfold_cv(v = 10, strata = N_lunch)

all_cores <- parallel::detectCores(logical = FALSE) - 30
library(doParallel)
cl <- makePSOCKcluster(all_cores)
registerDoParallel(cl)

# RandomForest

library(ranger)

rf_engine <- rand_forest(
  mode  = "regression",
  trees = 500,
  mtry  = tune(),
  min_n = tune()
) %>%  
  set_engine("ranger")

# Hyperparameter tunning : grid search

rf_params <- parameters(mtry(c(5, 15)), min_n(c(2, 10)))
rf_grid <- grid_max_entropy(rf_params, size = 50)

rf_tuned <- tune_grid(
  object       = rf_engine,
  preprocessor = train_recipe,
  resamples    = cv_folds,
  grid         = rf_grid,
  metrics      = metric_set(mae)
)

rf_tuned %>% show_best() # mtry = 6, CV mae = 70.2
(rf_best_params <- rf_tuned %>% select_best("mae"))

# Final lunch model

rf_engine_final <- rf_engine %>% finalize_model(rf_best_params)
final_lunch_model <- rf_engine_final %>% 
  fit(N_lunch ~ ., data = train_recipe %>% prep() %>% juice())

testset_final <- train_recipe %>% prep() %>% bake(test)

predicted_lunch <- final_lunch_model %>%
  predict.model_fit(testset_final) %>%
  unlist()

submission$`중식계` <- predicted_lunch
```

<hr>

<div style="margin-bottom:60px;">
</div>

## N_dinner

```{r}
# Make recipe

train_recipe <- train %>% 
  recipe(N_dinner ~ .) %>%
  step_rm(Date, Breakfast, Lunch, Dinner, N_lunch, Rate_lunch, Rate_dinner, starts_with("Lunch_"), starts_with("Dinner_")) %>%
  step_string2factor(all_nominal())

set.seed(2021)
cv_folds <- train %>% vfold_cv(v = 5, strata = N_dinner)

all_cores <- parallel::detectCores(logical = FALSE) - 30
library(doParallel)
cl <- makePSOCKcluster(all_cores)
registerDoParallel(cl)

# RandomForest

library(ranger)

rf_engine <- rand_forest(
  mode  = "regression",
  trees = 500,
  mtry  = tune(),
  min_n = tune()
) %>%  
  set_engine("ranger")

# Hyperparameter tunning : grid search

rf_params <- parameters(mtry(c(5, 15)), min_n(c(2, 10)))
rf_grid <- grid_max_entropy(rf_params, size = 50)

rf_tuned <- tune_grid(
  object       = rf_engine,
  preprocessor = train_recipe,
  resamples    = cv_folds,
  grid         = rf_grid,
  metrics      = metric_set(mae)
)

rf_tuned %>% show_best()
(rf_best_params <- rf_tuned %>% select_best("mae"))

# Final dinner model

rf_engine_final <- rf_engine %>% finalize_model(rf_best_params)
final_dinner_model <- rf_engine_final %>% 
  fit(N_dinner ~ ., data = train_recipe %>% prep() %>% juice())

testset_final <- train_recipe %>% prep() %>% bake(test)

predicted_dinner <- final_dinner_model %>%
  predict.model_fit(testset_final) %>%
  unlist()

submission$`석식계` <- predicted_dinner

submission %>% write_csv("./data/submission/submission_0717_first.csv")
```